runtime: go122

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: 500ms
  max_pending_latency: 5s
  max_concurrent_requests: 100

handlers:
- url: /favicon.ico
  static_files: app/static/favicon.png
  upload: app/static/favicon.png

- url: /static
  static_dir: app/static

- url: /push
  script: auto

- url: /.*
  script: auto
  secure: always
